### ISSUE TITLE
Bug: Incorrect Button labelling and font size mismatch

### ISSUE THREAD

**Issue by SiddhPurohit** [NeuroTechh/mainsite#13]
### What happened?

In the footer of each blog post, there appears to be a mis match of IconButtons with respect to their labelling and font size. 
The 'Next Post' button has a back arrow icon whereas the 'Previous Post' button has a forward arrow.
There is also a mismatch in the size of the labels, the label 'Next Post' is 14 px whereas 'Previous Page' is 16 px.

### Add screenshots

<img width="1265" alt="Screenshot 2024-06-06 at 3 40 59 PM" src="https://github.com/NeuroTechh/mainsite/assets/84131034/c7895b82-1b3d-4210-ae76-1e51cc877bc8">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by yashd-dev** [comment]
Fixed this issue, closing it
