### ISSUE TITLE
Feat: Adding a Newsletter System 

### ISSUE THREAD

**Issue by yashd-dev** [NeuroTechh/mainsite#4]
### What feature?

# Preface

By newsletter system, I mean a bi-weekly or monthly email to our users telling them about the blogs (or anything we made) 

# How to do it?

- We can start of by First Implementing an input for it under each blog
- Those Inputes will be stored somewhere (TO be decided, like sanity, supabase, Google Sheets)
- In the given time duration a corn job of sorts should trigger the email
- Or we don't want to do a corn job and do something custom that also will work
- For emails we can use resend for now, as we grow bigger we can use mailgun and their student benefit perks
- react-email can be used for styling the email but we are open to suggestions

These are all suggestions not hard and fast rules, feel free to raise concerns/suggestions. 

### Record

- [x] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by MananGandhi1810** [comment]
I'm ready to work upon it

**Comment by yashd-dev** [comment]
I was thinking of implementing this by first taking the input email into sanity, and monthly we manually run a script that fetches blogs from a given period from sanity itself. The way email is to be made is something we have to do rnd. React Email can be a good choice for it. 

So all we have to do is make a script that makes email by taking content fetched from sanity, putting it in a pre-designed template, and sending it by resend API. 

I am open to suggestions.

**Comment by MananGandhi1810** [comment]
yeah, seems like a good enough plan
